### ISSUE TITLE
代码报错

### ISSUE THREAD

**Issue by yuminjustin** [ecomfe/san-mui#69]
![image](https://user-images.githubusercontent.com/8414340/35723994-3135ab38-0837-11e8-8681-2b757b3d8e84.png)
![image](https://user-images.githubusercontent.com/8414340/35724007-38ae3c86-0837-11e8-8c03-78ce73f89110.png)

childs 这个书写有误  改成children 就正常了

**Comment by yuminjustin** [comment]
![image](https://user-images.githubusercontent.com/8414340/35724303-2e9b6a92-0838-11e8-9278-266755def60e.png)
![image](https://user-images.githubusercontent.com/8414340/35724663-7ee06ae2-0839-11e8-9a8a-dbe6e85dd691.png)


加上引号 就好了。。。。自己没测试过么。。。。

**Comment by asd123freedom** [comment]
目前的版本对应需要的san的版本是san的3.2.3，我们在package.json当中的peerdependencies配置项当中已经做了限制。由于san从3.2.x到3.4.x有一些break changes，所以san-mui对相应的升级也在开发中，预计年后发布。目前release版本还是需要指定san的版本是3.2.x版本。对给您造成的困扰表示迁移
