### ISSUE TITLE
组件引入问题

### ISSUE THREAD

**Issue by TeddyTsui** [ecomfe/san-mui#72]
目前使用版本1.1.1
组件不能一次性全部加载？
目前发现Table和List组件要单独加载
（List组件缺了API）

**Comment by asd123freedom** [comment]
您好，能用代码描述一下你在引用Table和List的时候遇到的问题吗？

**Comment by TeddyTsui** [comment]
`import {List, ListItem} from 'san-mui'`
`import {List, ListItem} from 'san-mui/lib/List'`
无法用第一种方式引用，需要用第二种方式单独引用，table组件也是如此

**Comment by asd123freedom** [comment]
了解，多谢反馈
